apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-prometheus-deployment
  labels:
    app: microservice-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-prometheus
  template:
    metadata:
      labels:
        app: microservice-prometheus
    spec:
      containers:
      - name: microservice-prometheus
        #change the image name
        image: prom/prometheus:v2.7.1
        args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus2/"
        ports:
          - containerPort: 9090
        imagePullPolicy: Always
        volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus2/
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-configuration
        - name: prometheus-storage-volume
          emptyDir: {}        
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-prometheus-service
  labels:
    app: microservice-prometheus
spec:
  clusterIP: None
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: microservice-prometheus