apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-speaker-deployment
  labels:
    app: microservice-speaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-speaker
  template:
    metadata:
      labels:
        app: microservice-speaker
    spec:
      containers:
      - name: microservice-speaker
        #change the image name
        image: journeycode/microservice-ol-speaker
        ports:
          - containerPort: 9080          
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-speaker-service
  annotations:
    mpmetrics: 'true'
  labels:
    app: microservice-speaker
spec:
  clusterIP: None
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: microservice-speaker
