apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-vote-deployment
  labels:
    app: microservice-vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-vote
  template:
    metadata:
      labels:
        app: microservice-vote
    spec:
      containers:
      - name: microservice-vote
        #change the image name
        image: journeycode/microservice-metrics-vote
        ports:
          - containerPort: 9080
        imagePullPolicy: Always
        env:
          - name: dbUsername
            valueFrom:
              secretKeyRef:
                name: cloudant-secret
                key: dbUsername
          - name: dbPassword
            valueFrom:
              secretKeyRef:
                name: cloudant-secret
                key: dbPassword
          - name: dbUrl
            value: http://cloudant-service:80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-vote-service
  annotations:
    mpmetrics: 'true'
  labels:
    app: microservice-vote
spec:
  clusterIP: None
  ports:
    - port: 9080
      targetPort: 9080
  selector:
    app: microservice-vote
